package fr.insideapp.sonarqube.objc.issues.oclint;

import fr.insideapp.sonarqube.apple.commons.ExtensionFileFilter;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.RegExUtils;
import org.sonar.api.utils.log.Logger;
import org.sonar.api.utils.log.Loggers;

import java.io.File;
import java.io.FileFilter;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Iterator;
import java.util.regex.Pattern;

public final class OCLintJSONDatabaseBuilder {

    private static final Pattern CLEAN_PATTERN = Pattern.compile("(\"-index-store-path.*DataStore\", |\"-index-unit-output-path.*\\.o\", )");

    private static final Logger LOGGER = Loggers.get(OCLintJSONDatabaseBuilder.class);

    public String build(File jsonCompilationDatabaseFolder) {
        // Retrieve the JSON Database fragments
        FileFilter jsonFileFilter = new ExtensionFileFilter("json");
        File[] jsonFiles = jsonCompilationDatabaseFolder.listFiles(jsonFileFilter);
        Iterator<File> jsonFilesIterator = Arrays.asList(jsonFiles).iterator();

        final StringBuilder compileCommandsBuilder = new StringBuilder();

        // Beginning the JSON Database
        compileCommandsBuilder.append("[");

        // For each JSON Database fragment
        while (jsonFilesIterator.hasNext()) {
            File jsonFile = jsonFilesIterator.next();
            try {
                // Getting the content
                String json = FileUtils.readFileToString(jsonFile, StandardCharsets.UTF_8);
                // Cleaning the JSON Database
                json = RegExUtils.removeAll(json, CLEAN_PATTERN);

                /* For the last one, we remove the trailing comma
                because fragments generated by clang have a comma before EOF
                and we want a valid JSON in the end
                 */
                if (!jsonFilesIterator.hasNext()) {
                    json = RegExUtils.removeFirst(json, ",$");
                }
                compileCommandsBuilder.append(json);
            } catch (Exception e) {
                LOGGER.error(e.getMessage(), e);
            }
        }

        // Ending the JSON Database
        compileCommandsBuilder.append("]");

        return compileCommandsBuilder.toString();
    }

}
