name: CI

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '13.4.1'

    - name: License Header Check
      run: mvn license:check

    - name: Build
      run: mvn -B package --file pom.xml

    - name: Analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=insideapp-oss \
        -Dsonar.projectKey=insideapp-oss_sonar-apple

    - name: Read version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

    - name: Upload snapshot release
      if: github.ref == 'refs/heads/develop'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/sonar-apple-plugin/target/*.jar
        tag: ${{env.version}}
        overwrite: true
        body: "Snapshot release"
        file_glob: true
        prerelease: true