name: Release

on:
  push:
    tags:
      - 0.*

jobs:
  build:

    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve tag name
        uses: olegtarasov/get-tag@v2.1.3
        id: tag_name

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2'

      - name: Set version
        run: mvn versions:set -DnewVersion=$GIT_TAG_NAME

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=insideapp-oss \
          -Dsonar.projectKey=insideapp-oss_sonar-apple

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/configuration/changelog-builder.json"
          ignorePreReleases: true
          fetchReviewers: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/sonar-apple-plugin/target/*.jar
          tag: ${{ steps.tag_name.outputs.tag }}
          overwrite: true
          body: ${{steps.build_changelog.outputs.changelog}}
          file_glob: true
